### ISSUE TITLE
Fix hanami script documentation

### ISSUE THREAD

**Issue by Atelier-Mirai** [bkuhlmann/hemo#1]
## Overview

I would like to learn 'HANAMI'. I have cloned your project and intend to follow the instructions. However, when I ran 'hanami db create' from the terminal, I got the following screenshot.

It seems to be failing to create the database, am I doing something wrong in the procedure?

## Screenshots/Screencasts

![ss 0005-02-19 午後9 14 48](https://user-images.githubusercontent.com/6257661/219947286-b1dc221a-49c8-4f7e-8986-bb2e5dfa1bce.png)

## Steps to Recreate

git clone https://github.com/bkuhlmann/hemo
cd hemo
bin/setup
hanami db create

## Environment

x86_64 % ruby --version
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin22]

x86_64 % psql --version
psql (PostgreSQL) 14.7 (Homebrew)

x86_64 % hanamismith --version
Hanamismith 0.4.0

x86_64 % bundler --version
Bundler version 2.4.6

Mac Studio 2022 Apple M1 Max. macOS 13.2.1 (22D68)

**Comment by bkuhlmann** [comment]
Hey Atelier, can you try using `bin/hanami db create` instaad? When I originally wrote the documentation, I assumed people were using the [Git Safe](https://alchemists.io/screencasts/git_safe) technique but if you are not aware of Git Safe, then the `hanami` script won't be on your path so you must manually add the `bin/` prefix to make it work.

I've also updated the documentation to account for this discrepancy as well.

Let me know if that resolves the issue for you?

**Comment by Atelier-Mirai** [comment]
Thank you for updating the document.

````
bin/hanami db create
/opt/homebrew/opt/rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/hanami-2.0.3/lib/hanami/settings.rb:174:in `initialize': Could not The following settings were invalid: (Hanami::Settings::InvalidSettingsError)

database_url: nil violates constraints (type?(String, nil) failed
(omitted)
```

Since you said database_url was missing, you can use
Referring to the official Hanami guide (https://guides.hanamirb.org/v2.0/introduction/getting-started/), I ran the following command

```
createdb hemo_development
createdb hemo_test
```

And since I needed two files (.env and .env.test) for the database_url, I created them with the following contents: ```` createdb hemo_development ```` createdb hemo_test ```

```
# .env 
DATABASE_URL=postgres://postgres:postgres@localhost:5432/hemo_development
```

```
# .env.test
DATABASE_URL=postgres://postgres:postgres@localhost:5432/hemo_test
```

```
bin/hanami db create
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL: role "postgres" does not exist
```

but I get an error message saying "role "postgres"". So I did ```` psql postgres ```.

```
bin/hanami db create
=> database hemo_development created
```
The database was successfully created.

Next, I executed the following command, and received an error message stating that I did not have sufficient permissions for encryption.

````
bin/hanami db migrate
/opt/homebrew/opt/rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sequel-5.65.0/lib/sequel/adapters/postgres.rb:171:in `exec': PG:: InsufficientPrivilege: ERROR: permission denied to create extension "pgcrypto" (Sequel::DatabaseError)
HINT: Must have CREATE privilege on current database to create this extension.
````

I really wish I had it, but I'm not sure if I should have it.
db/migrate/20230112210937_enable_crypto.rb
is now removed.

````
bin/hanami db migrate
=> database hemo_development migrated in 0.3381s
bin/hanami db seed
HANAMI_ENV=test bin/hanami db create
HANAMI_ENV=test bin/hanami db migrate
```

Finally, when I start the hanami server, I get an error message that the "tmp" directory is missing.

```` bin/hanami server 
bin/hanami server
[16453] Puma starting in cluster mode...
[16453] * Puma version: 6.1.0 (ruby 3.2.1-p31) ("The Way Up")
[16453] * Min threads: 5
[16453] * Max threads: 5
[16453] * Environment: development
[16453] * Master PID: 16453
[16453] * Workers: 10
[16453] * Restarts: (✔) hot (✖) phased
[16453] * Preloading application
[16453] * Listening on http://0.0.0.0:2300
[16453] Use Ctrl-C to stop
/opt/homebrew/opt/rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/puma-6.1.0/lib/puma/launcher.rb:307:in `write': No such file or directory @ rb_sysopen - tmp/server.pid (Errno::ENOENT)
```

So I ran ```` mkdir tmp ``` and it started successfully.

![ss 0005-02-20 午前3 11 12](https://user-images.githubusercontent.com/6257661/219968787-8182738e-1b1c-43e3-8e64-eed6829b2a76.png)


Thank you for creating a great template. I would like to deepen my learning.




Translated with www.DeepL.com/Translator (free version)

**Comment by bkuhlmann** [comment]
Nice work, it looks like the majority of your issues was with PostgreSQL. I've taken note of this as I think there might be a way to provide additional detection for a better experience in future versions. There are a couple of notes I'd like to highlight from your feedback above:

**Dotenv**

The [Dotenv](https://github.com/bkeepers/dotenv) files are generated for you by Hanamismith. For example:

``` 
hanamismith --build demo
cat demo/.env.development
DATABASE_URL=postgres://localhost/demo_development

cat demo/.env.test
DATABASE_URL=postgres://localhost/demo_test
```

This also means you shouldn't have had any need to manually create your databases. I suspect this has something to do with your PostgreSQL install. It might also have been possible that PostgreSQL wasn't running when attempting to create the databases?

**PostgreSQL Cryptography**

You got this error because PostgreSQL couldn't load the extension. You are running 14.7 while I'm running 15.2 but don't think that should matter. The migration should work unless there is something broken with your PostgreSQL installation. I'm considering removing the crypto migration in the next version based on this. It's not a strong requirement. Mostly a nicety.

---

Congratulations on getting the app up and running. :tada: I'm going to close this issue but feel free to continue the discussion if you like.
